name: Update the alt lists
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  mkalt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build
      run: |
        echo 0 > "status.txt" 
        pip3 install requests
        python combo.py
        echo 1 > "status.txt"
    - name: Commit & Push
      uses: actions-x/commit@v2
      with:
          email: noreply@example.com
          name: Update bot
          branch: main
          message: Update the comobo list
